# Generated by Django 5.1 on 2024-08-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yg_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='title',
            field=models.CharField(default='Default Session Title', max_length=100),
        ),
    ]
