# Generated by Django 5.1 on 2024-08-11 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yg_bookings', '0002_sessions_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='length',
        ),
        migrations.AddField(
            model_name='sessions',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessions',
            name='duration',
            field=models.DurationField(default='1hour 30mins'),
        ),
    ]
