# Generated by Django 5.1 on 2024-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yg_bookings', '0003_remove_sessions_length_sessions_booked_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='sessions',
            name='start_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='duration',
            field=models.DurationField(),
        ),
    ]
