# Generated by Django 5.1 on 2024-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yg_bookings', '0004_rename_time_sessions_end_time_sessions_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='start_time',
            field=models.DateTimeField(default='00:00:00'),
        ),
    ]
