# Generated by Django 5.1 on 2024-08-14 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yg_bookings', '0010_alter_sessions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 14)),
        ),
    ]
